---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - rds:
        command: facts
        instance_name: "{{ project_slug }}-database"
        region: "{{ region }}"
      register: database


    - name: Create Postgres Read-Only Replicant
      rds:
        command: replicate
        region: "{{ region }}"
        instance_name: "{{ project_slug }}-database-read-replicate"
        source_instance: "{{ project_slug }}-database"
      register: database-replicate


    - name: Create Metabass User with Privacy Preserving Access
      postgresql_user:
        login_host: "{{ database.instance.endpoint }}"
        login_user: "{{ pg_username }}"
        login_password: "{{ pg_password }}"
        db: intake
        name: "metabase"
        password: "{{ metabase_db_password }}"
        priv: "CONNECT"
        role_attr_flags: NOSUPERUSER
        no_password_changes: true


    - name: Give Metabase User permissions on Purged schema
      postgresql_privs:
        login_host: "{{ database.instance.endpoint }}"
        login_user: "{{ pg_app_username }}"
        login_password: "{{ pg_app_password }}"
        db: intake
        privs: USAGE
        type: schema
        objs: purged
        roles: metabase

    - rds:
        command: facts
        instance_name: "{{ project_slug }}-database-read-replicate"
        region: "{{ region }}"
      register: readonlydatabase
      until: not(readonlydatabase.instance.endpoint is none)
      retries: 20
      delay: 45
    - pause:
        seconds: 5
