---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "name_of_deploy"
      prompt: "Tell me again what you want to remove?"
      private: no
  tasks:
    - fail:
        msg: "That was a close one!"
      when: name_of_deploy != project_slug

    - name: Remove rds
      rds:
        command: delete
        region: "{{ region }}"
        instance_name: "{{ project_slug }}-database"
        wait: yes
        wait_timeout: 10000

    - name: Create S3 User with access the sync and media bucket[for rerun]
      iam:
        iam_type: user
        name: "{{ project_slug }}-sync-s3-user"
        state: present

    - name: Create S3 User for Application[for rerun]
      iam:
        iam_type: user
        name: "{{ project_slug }}-s3-user"
        state: present

    - name: Remove S3 permission for sync user on sync bucket
      iam_policy:
        policy_name: "{{ project_slug }}-sync-s3-policy"
        iam_name: "{{ project_slug }}-sync-s3-user"
        iam_type: user
        state: absent
        region: "{{ region }}"

    - name: Remove Read-Only S3 permission for sync User to pull media bucket
      iam_policy:
        policy_name: "{{ project_slug }}-s3-readonly-from-{{ clone_from_project_slug }}"
        iam_name: "{{ project_slug }}-sync-s3-user"
        iam_type: user
        state: absent
        region: "{{ region }}"
      when: clone_from_project_slug is defined

    - name: Remove S3 User with access the sync and media bucket
      iam:
        iam_type: user
        name: "{{ project_slug }}-sync-s3-user"
        state: absent

    - name: Remove S3 bucket which hold fixtures for data sync
      s3_bucket:
        name: "{{ project_slug }}-sync"
        state: absent
      when: clone_from_project_slug is undefined

    - name: Remove RDS subnet group
      rds_subnet_group:
        region: "{{ region }}"
        state: absent
        name: "{{ project_slug }}-rds-subnet-group"

    - name: Remove S3 permission for user
      iam_policy:
        policy_name: "{{ project_slug }}-s3-policy"
        iam_name: "{{ project_slug }}-s3-user"
        iam_type: user
        state: absent

    - name: Remove S3 User for Application
      iam:
        iam_type: user
        name: "{{ project_slug }}-s3-user"
        state: absent

    - name: Remove S3 bucket
      s3_bucket:
        name: "{{ project_slug }}-static-files"
        state: absent
        force: yes

    - name: Remove S3 bucket
      s3_bucket:
        name: "{{ project_slug }}-media-files"
        state: absent
        force: yes

    - name: Get VPC
      ec2_vpc_net:
        state: present
        name: "{{ project_slug }}-vpc"
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
        resource_tags: '{"Name":"{{ project_slug }}_vpc"}'
      register: vpc

    - name: Remove database security group
      ec2_group:
        name: "{{ project_slug }}-rds-security-group"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: absent
      register: "rds_sg"

    - name: Remove public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ project_slug }}_public_route"
        state: absent

    - name: Remove private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ project_slug }}_private_route"
        state: absent

    - name: Get Public Subnets
      ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          vpc_id: "{{ vpc.vpc.id }}"
          "tag:Type": "public"
      register: public_subnets

    - name: Get all nat gateways
      ec2_vpc_nat_gateway_facts:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc.vpc.id }}"
      register: nat_gateways

    - name: Remove NAT Gateways
      ec2_vpc_nat_gateway:
        state: absent
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        wait: yes
      with_items: "{{ nat_gateways.result }}"

    - name: Remove public subnet
      ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ vpc.vpc.id }}"
        az: "{{ az }}"
        region: "{{ region }}"
        cidr: 10.0.0.0/24

    - name: Remove  public subnet2
      ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ vpc.vpc.id }}"
        az: "{{ az2 }}"
        region: "{{ region }}"
        cidr: 10.0.1.0/24

    - name: Remove private subnet
      ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ vpc.vpc.id }}"
        az: "{{ az }}"
        region: "{{ region }}"
        cidr: 10.0.2.0/24

    - name: Remove private subnet2
      ec2_vpc_subnet:
        state: absent
        az: "{{ az2 }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.3.0/24

    - name: Remove IGW
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: absent

    - name: Remove NACL
      ec2_vpc_nacl:
        state: absent
        vpc_id: "{{ vpc.vpc.id }}"
        name: "{{ project_slug }}-nacl"
        region: "{{ region }}"

    - name: Remove Private NACL
      ec2_vpc_nacl:
        state: absent
        vpc_id: "{{ vpc.vpc.id }}"
        name: "{{ project_slug }}-nacl-public"
        region: "{{ region }}"

    - name: Remove vpc
      ec2_vpc_net:
        state: absent
        name: "{{ project_slug }}-vpc"
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
