---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create a file on the localhost
      copy:
        content: ""
        dest: /tmp/test.txt
        force: no
        mode: 0666
