---
- include: includes/build_project_dir.yml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install Newest Version of Zappa
      pip:
        name: zappa
        virtualenv: "{{ venv_path }}"
        virtualenv_python: python3.6
      environment:
        PYTHONPATH: "python3.6"

    - name: Create Zappa Settings File
      template:
        src: ../templates/undeploy_zappa_settings.json.j2
        dest: "{{ project_path  }}/zappa_settings.json"

    - name: Get VPC(will create if it doesn't exist, which isn't great)
      ec2_vpc_net:
        state: present
        name: "{{ project_slug }}-vpc"
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
        resource_tags: '{"Name":"{{ project_slug }}_vpc"}'
      register: vpc

    - name: Undeploy from Lambda
      shell: "source {{ venv_path }}/bin/activate && {{ venv_path }}/bin/zappa undeploy {{ environment_name }} --yes"
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
      environment:
        PYTHONPATH: "python3.6"
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

    - name: Remove Security Group for Lambda Application
      ec2_group:
        name: "{{ project_slug }}-lambda-security-group"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: absent

