---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set Environment Variables on Lambda function
      command: "aws lambda update-function-configuration  --region {{ region  }} --function-name intake-{{ environment_name }}  --environment '{{ lambda_environment|to_json }}'"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        PYTHONPATH: "python3.5"
      register: s3_user_keys

    - name: Delete Old Key for S3 User for Application
      command: "aws iam delete-access-key --access-key {{ s3_user.user_meta.access_keys[0].access_key_id }} --user-name {{ project_slug }}-s3-user"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        PYTHONPATH: "python3.5"

    - name: Run Migations
      shell: "source {{ venv_path }}/bin/activate && {{ venv_path }}/bin/zappa manage {{ environment_name }} migrate"
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
      environment:
        PYTHONPATH: "python3.6"
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

    - name: Run Migations(sometimes it needs to run twice because 30sec limit)
      shell: "source {{ venv_path }}/bin/activate && {{ venv_path }}/bin/zappa manage {{ environment_name }} migrate"
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
      environment:
        PYTHONPATH: "python3.6"
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

    - name: Load Essential Data
      shell: "source {{ venv_path }}/bin/activate && {{ venv_path }}/bin/zappa manage {{ environment_name }} load_essential_data"
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
      environment:
        PYTHONPATH: "python3.6"
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

    - name: Zappa Status from Lambda
      shell: "source {{ venv_path }}/bin/activate && {{ venv_path }}/bin/zappa status {{ environment_name }}"
      args:
        chdir: "{{ project_path }}"
        executable: /bin/bash
      environment:
        PYTHONPATH: "python3.6"
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      register: zappa_status
    - debug: var=zappa_status.stdout_lines

